///**
// * Autogenerated by Avro
// *
// * DO NOT EDIT DIRECTLY
// */
//package com.pol.payment_service.schema.avro;
//
//import org.apache.avro.message.BinaryMessageDecoder;
//import org.apache.avro.message.BinaryMessageEncoder;
//import org.apache.avro.message.SchemaStore;
//import org.apache.avro.specific.SpecificData;
//import org.apache.avro.util.Utf8;
//
//@org.apache.avro.specific.AvroGenerated
//public class PaymentSuccessfulEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
//  private static final long serialVersionUID = -5051151699532472632L;
//
//
//  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PaymentSuccessfulEvent\",\"namespace\":\"com.pol.payment_service.schema.avro\",\"fields\":[{\"name\":\"email\",\"type\":\"string\"},{\"name\":\"username\",\"type\":\"string\"},{\"name\":\"sub\",\"type\":\"string\"},{\"name\":\"paymentId\",\"type\":\"string\"},{\"name\":\"productId\",\"type\":\"string\"},{\"name\":\"orderId\",\"type\":\"string\"}]}");
//  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
//
//  private static final SpecificData MODEL$ = new SpecificData();
//
//  private static final BinaryMessageEncoder<PaymentSuccessfulEvent> ENCODER =
//      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);
//
//  private static final BinaryMessageDecoder<PaymentSuccessfulEvent> DECODER =
//      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);
//
//  /**
//   * Return the BinaryMessageEncoder instance used by this class.
//   * @return the message encoder used by this class
//   */
//  public static BinaryMessageEncoder<PaymentSuccessfulEvent> getEncoder() {
//    return ENCODER;
//  }
//
//  /**
//   * Return the BinaryMessageDecoder instance used by this class.
//   * @return the message decoder used by this class
//   */
//  public static BinaryMessageDecoder<PaymentSuccessfulEvent> getDecoder() {
//    return DECODER;
//  }
//
//  /**
//   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
//   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
//   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
//   */
//  public static BinaryMessageDecoder<PaymentSuccessfulEvent> createDecoder(SchemaStore resolver) {
//    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
//  }
//
//  /**
//   * Serializes this PaymentSuccessfulEvent to a ByteBuffer.
//   * @return a buffer holding the serialized data for this instance
//   * @throws java.io.IOException if this instance could not be serialized
//   */
//  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
//    return ENCODER.encode(this);
//  }
//
//  /**
//   * Deserializes a PaymentSuccessfulEvent from a ByteBuffer.
//   * @param b a byte buffer holding serialized data for an instance of this class
//   * @return a PaymentSuccessfulEvent instance decoded from the given buffer
//   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
//   */
//  public static PaymentSuccessfulEvent fromByteBuffer(
//      java.nio.ByteBuffer b) throws java.io.IOException {
//    return DECODER.decode(b);
//  }
//
//  private CharSequence email;
//  private CharSequence username;
//  private CharSequence sub;
//  private CharSequence paymentId;
//  private CharSequence productId;
//  private CharSequence orderId;
//
//  /**
//   * Default constructor.  Note that this does not initialize fields
//   * to their default values from the schema.  If that is desired then
//   * one should use <code>newBuilder()</code>.
//   */
//  public PaymentSuccessfulEvent() {}
//
//  /**
//   * All-args constructor.
//   * @param email The new value for email
//   * @param username The new value for username
//   * @param sub The new value for sub
//   * @param paymentId The new value for paymentId
//   * @param productId The new value for productId
//   * @param orderId The new value for orderId
//   */
//  public PaymentSuccessfulEvent(CharSequence email, CharSequence username, CharSequence sub, CharSequence paymentId, CharSequence productId, CharSequence orderId) {
//    this.email = email;
//    this.username = username;
//    this.sub = sub;
//    this.paymentId = paymentId;
//    this.productId = productId;
//    this.orderId = orderId;
//  }
//
//  @Override
//  public SpecificData getSpecificData() { return MODEL$; }
//
//  @Override
//  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
//
//  // Used by DatumWriter.  Applications should not call.
//  @Override
//  public Object get(int field$) {
//    switch (field$) {
//    case 0: return email;
//    case 1: return username;
//    case 2: return sub;
//    case 3: return paymentId;
//    case 4: return productId;
//    case 5: return orderId;
//    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
//    }
//  }
//
//  // Used by DatumReader.  Applications should not call.
//  @Override
//  @SuppressWarnings(value="unchecked")
//  public void put(int field$, Object value$) {
//    switch (field$) {
//    case 0: email = (CharSequence)value$; break;
//    case 1: username = (CharSequence)value$; break;
//    case 2: sub = (CharSequence)value$; break;
//    case 3: paymentId = (CharSequence)value$; break;
//    case 4: productId = (CharSequence)value$; break;
//    case 5: orderId = (CharSequence)value$; break;
//    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
//    }
//  }
//
//  /**
//   * Gets the value of the 'email' field.
//   * @return The value of the 'email' field.
//   */
//  public CharSequence getEmail() {
//    return email;
//  }
//
//
//  /**
//   * Sets the value of the 'email' field.
//   * @param value the value to set.
//   */
//  public void setEmail(CharSequence value) {
//    this.email = value;
//  }
//
//  /**
//   * Gets the value of the 'username' field.
//   * @return The value of the 'username' field.
//   */
//  public CharSequence getUsername() {
//    return username;
//  }
//
//
//  /**
//   * Sets the value of the 'username' field.
//   * @param value the value to set.
//   */
//  public void setUsername(CharSequence value) {
//    this.username = value;
//  }
//
//  /**
//   * Gets the value of the 'sub' field.
//   * @return The value of the 'sub' field.
//   */
//  public CharSequence getSub() {
//    return sub;
//  }
//
//
//  /**
//   * Sets the value of the 'sub' field.
//   * @param value the value to set.
//   */
//  public void setSub(CharSequence value) {
//    this.sub = value;
//  }
//
//  /**
//   * Gets the value of the 'paymentId' field.
//   * @return The value of the 'paymentId' field.
//   */
//  public CharSequence getPaymentId() {
//    return paymentId;
//  }
//
//
//  /**
//   * Sets the value of the 'paymentId' field.
//   * @param value the value to set.
//   */
//  public void setPaymentId(CharSequence value) {
//    this.paymentId = value;
//  }
//
//  /**
//   * Gets the value of the 'productId' field.
//   * @return The value of the 'productId' field.
//   */
//  public CharSequence getProductId() {
//    return productId;
//  }
//
//
//  /**
//   * Sets the value of the 'productId' field.
//   * @param value the value to set.
//   */
//  public void setProductId(CharSequence value) {
//    this.productId = value;
//  }
//
//  /**
//   * Gets the value of the 'orderId' field.
//   * @return The value of the 'orderId' field.
//   */
//  public CharSequence getOrderId() {
//    return orderId;
//  }
//
//
//  /**
//   * Sets the value of the 'orderId' field.
//   * @param value the value to set.
//   */
//  public void setOrderId(CharSequence value) {
//    this.orderId = value;
//  }
//
//  /**
//   * Creates a new PaymentSuccessfulEvent RecordBuilder.
//   * @return A new PaymentSuccessfulEvent RecordBuilder
//   */
//  public static Builder newBuilder() {
//    return new Builder();
//  }
//
//  /**
//   * Creates a new PaymentSuccessfulEvent RecordBuilder by copying an existing Builder.
//   * @param other The existing builder to copy.
//   * @return A new PaymentSuccessfulEvent RecordBuilder
//   */
//  public static Builder newBuilder(Builder other) {
//    if (other == null) {
//      return new Builder();
//    } else {
//      return new Builder(other);
//    }
//  }
//
//  /**
//   * Creates a new PaymentSuccessfulEvent RecordBuilder by copying an existing PaymentSuccessfulEvent instance.
//   * @param other The existing instance to copy.
//   * @return A new PaymentSuccessfulEvent RecordBuilder
//   */
//  public static Builder newBuilder(PaymentSuccessfulEvent other) {
//    if (other == null) {
//      return new Builder();
//    } else {
//      return new Builder(other);
//    }
//  }
//
//  /**
//   * RecordBuilder for PaymentSuccessfulEvent instances.
//   */
//  @org.apache.avro.specific.AvroGenerated
//  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PaymentSuccessfulEvent>
//    implements org.apache.avro.data.RecordBuilder<PaymentSuccessfulEvent> {
//
//    private CharSequence email;
//    private CharSequence username;
//    private CharSequence sub;
//    private CharSequence paymentId;
//    private CharSequence productId;
//    private CharSequence orderId;
//
//    /** Creates a new Builder */
//    private Builder() {
//      super(SCHEMA$, MODEL$);
//    }
//
//    /**
//     * Creates a Builder by copying an existing Builder.
//     * @param other The existing Builder to copy.
//     */
//    private Builder(Builder other) {
//      super(other);
//      if (isValidValue(fields()[0], other.email)) {
//        this.email = data().deepCopy(fields()[0].schema(), other.email);
//        fieldSetFlags()[0] = other.fieldSetFlags()[0];
//      }
//      if (isValidValue(fields()[1], other.username)) {
//        this.username = data().deepCopy(fields()[1].schema(), other.username);
//        fieldSetFlags()[1] = other.fieldSetFlags()[1];
//      }
//      if (isValidValue(fields()[2], other.sub)) {
//        this.sub = data().deepCopy(fields()[2].schema(), other.sub);
//        fieldSetFlags()[2] = other.fieldSetFlags()[2];
//      }
//      if (isValidValue(fields()[3], other.paymentId)) {
//        this.paymentId = data().deepCopy(fields()[3].schema(), other.paymentId);
//        fieldSetFlags()[3] = other.fieldSetFlags()[3];
//      }
//      if (isValidValue(fields()[4], other.productId)) {
//        this.productId = data().deepCopy(fields()[4].schema(), other.productId);
//        fieldSetFlags()[4] = other.fieldSetFlags()[4];
//      }
//      if (isValidValue(fields()[5], other.orderId)) {
//        this.orderId = data().deepCopy(fields()[5].schema(), other.orderId);
//        fieldSetFlags()[5] = other.fieldSetFlags()[5];
//      }
//    }
//
//    /**
//     * Creates a Builder by copying an existing PaymentSuccessfulEvent instance
//     * @param other The existing instance to copy.
//     */
//    private Builder(PaymentSuccessfulEvent other) {
//      super(SCHEMA$, MODEL$);
//      if (isValidValue(fields()[0], other.email)) {
//        this.email = data().deepCopy(fields()[0].schema(), other.email);
//        fieldSetFlags()[0] = true;
//      }
//      if (isValidValue(fields()[1], other.username)) {
//        this.username = data().deepCopy(fields()[1].schema(), other.username);
//        fieldSetFlags()[1] = true;
//      }
//      if (isValidValue(fields()[2], other.sub)) {
//        this.sub = data().deepCopy(fields()[2].schema(), other.sub);
//        fieldSetFlags()[2] = true;
//      }
//      if (isValidValue(fields()[3], other.paymentId)) {
//        this.paymentId = data().deepCopy(fields()[3].schema(), other.paymentId);
//        fieldSetFlags()[3] = true;
//      }
//      if (isValidValue(fields()[4], other.productId)) {
//        this.productId = data().deepCopy(fields()[4].schema(), other.productId);
//        fieldSetFlags()[4] = true;
//      }
//      if (isValidValue(fields()[5], other.orderId)) {
//        this.orderId = data().deepCopy(fields()[5].schema(), other.orderId);
//        fieldSetFlags()[5] = true;
//      }
//    }
//
//    /**
//      * Gets the value of the 'email' field.
//      * @return The value.
//      */
//    public CharSequence getEmail() {
//      return email;
//    }
//
//
//    /**
//      * Sets the value of the 'email' field.
//      * @param value The value of 'email'.
//      * @return This builder.
//      */
//    public Builder setEmail(CharSequence value) {
//      validate(fields()[0], value);
//      this.email = value;
//      fieldSetFlags()[0] = true;
//      return this;
//    }
//
//    /**
//      * Checks whether the 'email' field has been set.
//      * @return True if the 'email' field has been set, false otherwise.
//      */
//    public boolean hasEmail() {
//      return fieldSetFlags()[0];
//    }
//
//
//    /**
//      * Clears the value of the 'email' field.
//      * @return This builder.
//      */
//    public Builder clearEmail() {
//      email = null;
//      fieldSetFlags()[0] = false;
//      return this;
//    }
//
//    /**
//      * Gets the value of the 'username' field.
//      * @return The value.
//      */
//    public CharSequence getUsername() {
//      return username;
//    }
//
//
//    /**
//      * Sets the value of the 'username' field.
//      * @param value The value of 'username'.
//      * @return This builder.
//      */
//    public Builder setUsername(CharSequence value) {
//      validate(fields()[1], value);
//      this.username = value;
//      fieldSetFlags()[1] = true;
//      return this;
//    }
//
//    /**
//      * Checks whether the 'username' field has been set.
//      * @return True if the 'username' field has been set, false otherwise.
//      */
//    public boolean hasUsername() {
//      return fieldSetFlags()[1];
//    }
//
//
//    /**
//      * Clears the value of the 'username' field.
//      * @return This builder.
//      */
//    public Builder clearUsername() {
//      username = null;
//      fieldSetFlags()[1] = false;
//      return this;
//    }
//
//    /**
//      * Gets the value of the 'sub' field.
//      * @return The value.
//      */
//    public CharSequence getSub() {
//      return sub;
//    }
//
//
//    /**
//      * Sets the value of the 'sub' field.
//      * @param value The value of 'sub'.
//      * @return This builder.
//      */
//    public Builder setSub(CharSequence value) {
//      validate(fields()[2], value);
//      this.sub = value;
//      fieldSetFlags()[2] = true;
//      return this;
//    }
//
//    /**
//      * Checks whether the 'sub' field has been set.
//      * @return True if the 'sub' field has been set, false otherwise.
//      */
//    public boolean hasSub() {
//      return fieldSetFlags()[2];
//    }
//
//
//    /**
//      * Clears the value of the 'sub' field.
//      * @return This builder.
//      */
//    public Builder clearSub() {
//      sub = null;
//      fieldSetFlags()[2] = false;
//      return this;
//    }
//
//    /**
//      * Gets the value of the 'paymentId' field.
//      * @return The value.
//      */
//    public CharSequence getPaymentId() {
//      return paymentId;
//    }
//
//
//    /**
//      * Sets the value of the 'paymentId' field.
//      * @param value The value of 'paymentId'.
//      * @return This builder.
//      */
//    public Builder setPaymentId(CharSequence value) {
//      validate(fields()[3], value);
//      this.paymentId = value;
//      fieldSetFlags()[3] = true;
//      return this;
//    }
//
//    /**
//      * Checks whether the 'paymentId' field has been set.
//      * @return True if the 'paymentId' field has been set, false otherwise.
//      */
//    public boolean hasPaymentId() {
//      return fieldSetFlags()[3];
//    }
//
//
//    /**
//      * Clears the value of the 'paymentId' field.
//      * @return This builder.
//      */
//    public Builder clearPaymentId() {
//      paymentId = null;
//      fieldSetFlags()[3] = false;
//      return this;
//    }
//
//    /**
//      * Gets the value of the 'productId' field.
//      * @return The value.
//      */
//    public CharSequence getProductId() {
//      return productId;
//    }
//
//
//    /**
//      * Sets the value of the 'productId' field.
//      * @param value The value of 'productId'.
//      * @return This builder.
//      */
//    public Builder setProductId(CharSequence value) {
//      validate(fields()[4], value);
//      this.productId = value;
//      fieldSetFlags()[4] = true;
//      return this;
//    }
//
//    /**
//      * Checks whether the 'productId' field has been set.
//      * @return True if the 'productId' field has been set, false otherwise.
//      */
//    public boolean hasProductId() {
//      return fieldSetFlags()[4];
//    }
//
//
//    /**
//      * Clears the value of the 'productId' field.
//      * @return This builder.
//      */
//    public Builder clearProductId() {
//      productId = null;
//      fieldSetFlags()[4] = false;
//      return this;
//    }
//
//    /**
//      * Gets the value of the 'orderId' field.
//      * @return The value.
//      */
//    public CharSequence getOrderId() {
//      return orderId;
//    }
//
//
//    /**
//      * Sets the value of the 'orderId' field.
//      * @param value The value of 'orderId'.
//      * @return This builder.
//      */
//    public Builder setOrderId(CharSequence value) {
//      validate(fields()[5], value);
//      this.orderId = value;
//      fieldSetFlags()[5] = true;
//      return this;
//    }
//
//    /**
//      * Checks whether the 'orderId' field has been set.
//      * @return True if the 'orderId' field has been set, false otherwise.
//      */
//    public boolean hasOrderId() {
//      return fieldSetFlags()[5];
//    }
//
//
//    /**
//      * Clears the value of the 'orderId' field.
//      * @return This builder.
//      */
//    public Builder clearOrderId() {
//      orderId = null;
//      fieldSetFlags()[5] = false;
//      return this;
//    }
//
//    @Override
//    @SuppressWarnings("unchecked")
//    public PaymentSuccessfulEvent build() {
//      try {
//        PaymentSuccessfulEvent record = new PaymentSuccessfulEvent();
//        record.email = fieldSetFlags()[0] ? this.email : (CharSequence) defaultValue(fields()[0]);
//        record.username = fieldSetFlags()[1] ? this.username : (CharSequence) defaultValue(fields()[1]);
//        record.sub = fieldSetFlags()[2] ? this.sub : (CharSequence) defaultValue(fields()[2]);
//        record.paymentId = fieldSetFlags()[3] ? this.paymentId : (CharSequence) defaultValue(fields()[3]);
//        record.productId = fieldSetFlags()[4] ? this.productId : (CharSequence) defaultValue(fields()[4]);
//        record.orderId = fieldSetFlags()[5] ? this.orderId : (CharSequence) defaultValue(fields()[5]);
//        return record;
//      } catch (org.apache.avro.AvroMissingFieldException e) {
//        throw e;
//      } catch (Exception e) {
//        throw new org.apache.avro.AvroRuntimeException(e);
//      }
//    }
//  }
//
//  @SuppressWarnings("unchecked")
//  private static final org.apache.avro.io.DatumWriter<PaymentSuccessfulEvent>
//    WRITER$ = (org.apache.avro.io.DatumWriter<PaymentSuccessfulEvent>)MODEL$.createDatumWriter(SCHEMA$);
//
//  @Override public void writeExternal(java.io.ObjectOutput out)
//    throws java.io.IOException {
//    WRITER$.write(this, SpecificData.getEncoder(out));
//  }
//
//  @SuppressWarnings("unchecked")
//  private static final org.apache.avro.io.DatumReader<PaymentSuccessfulEvent>
//    READER$ = (org.apache.avro.io.DatumReader<PaymentSuccessfulEvent>)MODEL$.createDatumReader(SCHEMA$);
//
//  @Override public void readExternal(java.io.ObjectInput in)
//    throws java.io.IOException {
//    READER$.read(this, SpecificData.getDecoder(in));
//  }
//
//  @Override protected boolean hasCustomCoders() { return true; }
//
//  @Override public void customEncode(org.apache.avro.io.Encoder out)
//    throws java.io.IOException
//  {
//    out.writeString(this.email);
//
//    out.writeString(this.username);
//
//    out.writeString(this.sub);
//
//    out.writeString(this.paymentId);
//
//    out.writeString(this.productId);
//
//    out.writeString(this.orderId);
//
//  }
//
//  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
//    throws java.io.IOException
//  {
//    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
//    if (fieldOrder == null) {
//      this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);
//
//      this.username = in.readString(this.username instanceof Utf8 ? (Utf8)this.username : null);
//
//      this.sub = in.readString(this.sub instanceof Utf8 ? (Utf8)this.sub : null);
//
//      this.paymentId = in.readString(this.paymentId instanceof Utf8 ? (Utf8)this.paymentId : null);
//
//      this.productId = in.readString(this.productId instanceof Utf8 ? (Utf8)this.productId : null);
//
//      this.orderId = in.readString(this.orderId instanceof Utf8 ? (Utf8)this.orderId : null);
//
//    } else {
//      for (int i = 0; i < 6; i++) {
//        switch (fieldOrder[i].pos()) {
//        case 0:
//          this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);
//          break;
//
//        case 1:
//          this.username = in.readString(this.username instanceof Utf8 ? (Utf8)this.username : null);
//          break;
//
//        case 2:
//          this.sub = in.readString(this.sub instanceof Utf8 ? (Utf8)this.sub : null);
//          break;
//
//        case 3:
//          this.paymentId = in.readString(this.paymentId instanceof Utf8 ? (Utf8)this.paymentId : null);
//          break;
//
//        case 4:
//          this.productId = in.readString(this.productId instanceof Utf8 ? (Utf8)this.productId : null);
//          break;
//
//        case 5:
//          this.orderId = in.readString(this.orderId instanceof Utf8 ? (Utf8)this.orderId : null);
//          break;
//
//        default:
//          throw new java.io.IOException("Corrupt ResolvingDecoder.");
//        }
//      }
//    }
//  }
//}
//
//
//
//
//
//
//
//
//
//
